### ISSUE TITLE
forticleint legacy APK

### ISSUE THREAD

**Issue by amineevo** [APKLab/APKLab#124]
Hello everyone

 is this program can help me to extract data from a legacy forticlient apk? because I have been looking for a solution for a week to extract the data file from the application but without success. if anyone can help me on this. the goal of doing this is to deploy the same data on multiple tablets by an MDM. thank you in advance.

https://linkpicture.com/view.php?img=LPic6060646e02164579242038

**Comment by Surendrajat** [comment]
@amineevo Not really. To obtain data from an existing application you will need to have ROOT access in most cases unless the data in stored in `/sdcard/Android/your_apk/`. If it's in `/data/` then you'll need to ROOT your device.
