### ISSUE TITLE
Edit Package Name APK

### ISSUE THREAD

**Issue by Pabubung** [APKLab/APKLab#132]
It is possible to edit package name in apklab? and How? Thanks

**Comment by Surendrajat** [comment]
Yes. Simply change `package='com.blah.blah'` to something you like in `AndroidManifest.xml` file and recompile.

Tip: if your intent is to install both APKs simultaneously then some other things like receiver names etc. might also conflict, but they are there in the same file, so you can easily change those as well.

**Comment by Pabubung** [comment]
Got it, It installed successfully. Thank you @Surendrajat
