### ISSUE TITLE
Add option to disable git

### ISSUE THREAD

**Issue by zackmark29** [APKLab/APKLab#144]
I just found this great extension. Is it possible to add option also to disable automatically creating git?
Thank you

**Comment by Surendrajat** [comment]
@zackmark29 you can disable that from VS Code settings:

![image](https://user-images.githubusercontent.com/11215000/132494859-6bd11ba7-6d31-4e4f-b583-bfb4a4e0bad1.png)

**Comment by zackmark29** [comment]
> @zackmark29 you can disable that from VS Code settings:
> 
> ![image](https://user-images.githubusercontent.com/11215000/132494859-6bd11ba7-6d31-4e4f-b583-bfb4a4e0bad1.png)

Ah thanks.
