### ISSUE TITLE
File system provider for decompileFs:/ is not available

### ISSUE THREAD

**Issue by Heraghon** [APKLab/APKLab#151]
**Describe the bug**
When opening an APK with CTR+Shift+P, no filebrowser shows up, and an error popup stating "File system provider for decompileFs:/ is not available." pops in the right bottom corner of VS Code

**To Reproduce**

1. Go to the vs code command palette
2. Choose on 'APKLab: Open an APK'
3. See error

**Expected behavior**
A file browser should pop up, allowing me to select the apk file to open

**Console Logs**

<details>

APKLAB: no APK file was chosen

</details>

**System Information:**

- OS: Windows 10 Pro
- VSCode Version: 1.62.2

**Comment by Surendrajat** [comment]
This does not look like an APKLab bug.

I believe you're using this [decompiler extension](https://github.com/tintinweb/vscode-decompiler), which creates this temporary `decompileFs:/` file system which may not be available as regular FS. Can you confirm if this is the case?

**Comment by Heraghon** [comment]
Hmm, I indeed had it installed but uninstalled it before using APKLab. Now the bug is gone so it might have been because I needed to restart my computer and/or VS Code in order to stop the conflict. Thanks for the answer !
