### ISSUE TITLE
How to pull apk file with its .so files?

### ISSUE THREAD

**Issue by VicoErv** [APKLab/APKLab#152]
I tried to decompile my app that has external library files. But when I pull using adb, and decompile it, the .so files are not included anymore.

**Comment by Surendrajat** [comment]
You can simply extract the APK to get it because the `.so` libs are extracted to some weird looking path while it's installed.

**Comment by VicoErv** [comment]
thank's for your response.
Then I want to recompile modified smali, how to build it including the .so files?

**Comment by Surendrajat** [comment]
APKLab and apktool both pick the libs dir from extracted apk while building.
