### ISSUE TITLE
When APKLab initialize Git, It always initialize it in my VScode installation directory.

### ISSUE THREAD

**Issue by Forgo7ten** [APKLab/APKLab#153]
**Describe the bug**
When I decompile an apk, it always initializes git in my vscode installation directory whenever it's time to initialize git.
When APKLab initialize Git, It always initialize it in my VScode installation directory

**To Reproduce**

1. I Click on”open an APK“
2. Select apK file (any one)
3. Check ”decompile_java“ and "--only-main-classes"

**Expected behavior**
It does not initialize Git in the decompilated directory as expected

**Console Logs**

<details>

```bash
----------------------------------------------------------------------------------------
Decoding apkxxx.apk into c:\Users\User\Desktop\ts\debug\apkxxx
----------------------------------------------------------------------------------------
java -jar C:\Users\User\.apklab\apktool_2.6.0.jar d c:\Users\User\Desktop\ts\debug\apkxxx.apk -o c:\Users\User\Desktop\ts\debug\apkxxx --only-main-classes
I: Using Apktool 2.6.0 on apkxxx.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\User\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes4.dex...
I: Copying raw assets/audience_network.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
Decoding process was successful
----------------------------------------------------------------------------------------------------
Decompiling apkxxx.apk into c:\Users\User\Desktop\ts\debug\apkxxx\java_src
----------------------------------------------------------------------------------------------------
C:\Users\User\.apklab\jadx-1.2.0\bin\jadx.bat -r -q -v -ds c:\Users\User\Desktop\ts\debug\apkxxx\java_src c:\Users\User\Desktop\ts\debug\apkxxx.apk
Decompiling process was successful
----------------------------------------------------------------------------------
Initializing c:\Users\User\Desktop\ts\debug\apkxxx as Git repository
----------------------------------------------------------------------------------
cd "c:\Users\User\Desktop\ts\debug\apkxxx" && git init && git config core.safecrlf false && git add -A && git commit -q -m "Initial APKLab project" 
Reinitialized existing Git repository in E:/code/Microsoft VS Code/.git/
On branch main
nothing to commit, working tree clean
Initializing Git process exited with code 1
```

</details>

**System Information:**

- OS: Window 10
- VSCode Version: 1.63.1

**Additional context**

**Comment by Forgo7ten** [comment]
And if I delete the git repository located in the vscode installation directory
Its log looks something like this

```
cd "c:\Users\user\Desktop\ap" && git init && git config core.safecrlf false && git add -A && git commit -q -m "Initial APKLab project" 
Initialized empty Git repository in E:/code/Microsoft VS Code/.git/
Initializing Git process was successful
```
I'm sure it's a BUG, but I don't know why only I have this problem?

**Comment by Surendrajat** [comment]
@Forgo7ten It's strange as it clearly prints the correct commands first and then tries to execute them. It seems like a Windows specific bug to me, and I don't have a Windows machine to debug it.
Can you clone the source repo and try to debug the extension to see what's the issue? You will need to uninstall the extension first.

**Comment by Forgo7ten** [comment]
@Surendrajat I'm very sorry. I'm a beginner in programming. I cloned the repository, tried it, and ran the following commands.
```bash
npm install -g yarn
npm install -g typescript
npm install
```
I set the breakpoint in the `git.ts` file. And use the “run extension” to run. Then it looks like this.
<details>
```bash
> Executing task in folder APKLab: npm run watch <


> apklab@1.5.0 watch
> webpack --watch   

    [webpack-cli] Compiler starting... 
    [webpack-cli] Compiler is using config: 'C:\Users\Palmer\Desktop\ts\APKLab\webpack.config.js'
asset extension.js 1.25 MiB [compared for emit] (name: main) 1 related asset
runtime modules 1.11 KiB 5 modules
modules by path ./node_modules/ 1.08 MiB 481 modules
modules by path ./src/ 55.4 KiB
  modules by path ./src/tools/*.ts 22.3 KiB 7 modules
  modules by path ./src/utils/*.ts 22.6 KiB 5 modules
  modules by path ./src/*.ts 9.13 KiB
    ./src/extension.ts 3.16 KiB [built] [code generated]
    ./src/interface.ts 5.36 KiB [built] [code generated]
    ./src/any-observable-fix.ts 624 bytes [built] [code generated]
  modules by path ./src/data/ 1.37 KiB
    ./src/data/constants.ts 721 bytes [built] [code generated]
    ./src/data/config.json 684 bytes [built] [code generated]
15 modules
webpack 5.57.1 compiled successfully in 6550 ms
    [webpack-cli] Compiler finished
    [webpack-cli] Compiler is watching files for updates...
```
</details>
And vscode has an error pop-up: `The task 'npm: watch' cannot be tracked. Make sure to have a problem matcher defined.`
---
Then I tried the second option: Extension Tests
<details>
```bash
> Executing task in folder APKLab: npm run pretest <


> apklab@1.5.0 pretest
> yarn compile        

yarn run v1.22.17
warning apklab@1.5.0: The engine "vscode" appears to be invalid.
$ tsc -p ./
Done in 5.68s.

Terminal will be reused by tasks, press any key to close it.
```
And a vscode window flashes by, and the next debugging terminal looks like the following picture
![image](https://user-images.githubusercontent.com/57509907/149131595-81eddbe3-3ede-48a7-bcda-0cdc9b0af75a.png)
</details>

I think that's why I didn't modify the "launch.json" file? At least the APK files that need to be decompiled are not added.
But I can only do so much. I don't have much experience in developing vscode plug-ins.
Of course I'd be happy to help, but as you can see, I'm just a beginner. If you could give me a debugging process, I think it would be much more helpful.

**Comment by Surendrajat** [comment]
@Forgo7ten what you did with first option was almost correct. The problem is, we depend on [an extension which was removed and published under another namespace](https://marketplace.visualstudio.com/items?itemName=amodio.tsl-problem-matcher). So you just need to install this extension, and it'll provide the needed problem-matcher for debugging to start. I'm going to update the recommended extension list anyway.

Also, while `npm install` works, we use `yarn` now for that. So you need to just do the following after cloning:
```bash
npm install -g yarn
yarn
```

----
As for the extension tests, well you can safely ignore those. Those are just tests for features. The missing files can be obtained by doing `git clone --recurse-submodules ...`.

**Comment by Forgo7ten** [comment]
I found it!
For windows, the command "cd" cannot directly jump between different disks. There is no problem with the commands of the program. Like the picture below, I copied the two commands generated by the program to execute. It's just a missing command to switch disks, like "C:". In Windows, only the "cd" command on the same disk can jump to the specified folder.
![image](https://user-images.githubusercontent.com/57509907/149150034-b150cfd3-73e3-40a3-a8ae-6625aaaab119.png)
So I simply modified the program as follows.
![image](https://user-images.githubusercontent.com/57509907/149151329-8b1d97f7-2476-4e78-93a8-0a18ad6b4908.png)
As you can see, it's pretty simple, but it does solve the problem. But this is a problem unique to Windows. So I suggest you add a setting to let the user choose the platform, and then add a judgment in the code. If it is a windows platform, you need to add an additional command to switch the disk. This is very simple, just need to intercept the first two characters of the path , like I did above.
If you have a better idea, that would be great.

---

One more question, I have some OCD. How should I uninstall the debug environment?
Uninstall the corresponding vscode extension, `yarn`, delete the folder, right?

**Comment by Forgo7ten** [comment]
Yes, it works great. Whether it is the same drive or between different drives.
![image](https://user-images.githubusercontent.com/57509907/149259032-232ceadd-466d-40b8-8bd3-750e52dd0a3b.png)
But it doesn't seem like a workaround for a universal platform: it doesn't work on linux

**Comment by Surendrajat** [comment]
Cool. Let's go with that for now.

Yeah. I know it's not cross-platform but, at this point, the codebase and issue tracker is full of Windows quirks and adding one more won't hurt that much : )
