### ISSUE TITLE
cant open anything (no such file or directory)

### ISSUE THREAD

**Issue by stvpls01** [APKLab/APKLab#162]
**Describe the bug**
hi im new to this, basically every time i try opening any apk it says that it doesnt exist

**To Reproduce**

ctrl shift p and open apk 
select the apk then open and enter and it gives the error

**Expected behavior**
well to open, no idea how its like cause it never worked so idk haha

**Console Logs**
Decoding subito-it.apk into c:\Users\User\Desktop\subito-it
-----------------------------------------------------------
java -jar C:\Users\User\.apklab\apktool_2.6.0.jar d c:\Users\User\Desktop\subito-it.apk -o c:\Users\User\Desktop\subito-it --only-main-classes
Error: spawn java ENOENT
Error: Initializing project dir as Git repository: ENOENT: no such file or directory, open 'c:\Users\User\Desktop\subito-it\.gitignore'

Please paste all your console output here... between the details HTML tags!

</details>

**System Information:**

- OS: windows 7 pro
- VSCode Version: 1.64

**Additional context**

**Comment by Surendrajat** [comment]
Looks like you don't have Java installed. You can download it from adoptopenjdk.com
