### ISSUE TITLE
When creating a git repository, it takes too long.

### ISSUE THREAD

**Issue by Forgo7ten** [APKLab/APKLab#164]
**Describe the bug**
When creating a git repository, it takes too long. In my statistics, it usually takes an average of 30 seconds to work. However, the execution of the 'git init' command takes less than a second.

**To Reproduce**
I made a video of the relevant steps.
[apklab.mp4 in google drive](https://drive.google.com/file/d/1Nh1lYycekOrAuqAOW8uXotkcBg-jbrDX/view?usp=sharing)

In this video, From the 15th second, it executes the 'git init' command until the 41st second, which takes 26 seconds. My previous tests sometimes took 35 seconds to execute this command. But it's just an order.
From the 47th second, I started to switch to the corresponding directory to manually execute the 'git init' command, but it took less than 1 second. I checked the source code and probably spent extra time in 'await executeprocess'. But why?

**Expected behavior**

Correctly speaking, this step takes less than a second to execute the 'git init' command. Then the execution time of this step should not be about 30 seconds.

**Console Logs**

Nothing different from normal output

**System Information:**

- OS:  Windows 10 professional edition 21H1 19043.1415
- VSCode Version: 1.63.2

**Additional context**

This is an obvious time consumption. Obviously, it can't be regarded as a bug, but I think it should be improved

**Comment by Surendrajat** [comment]
I think you forgot the `git add` and `git commit` steps.
https://github.com/APKLab/APKLab/blob/b099ec44458c78fdae2532e7bd30b72b32eb21bd/src/tools/git.ts#L32

From my experience, this is always slower on Windows as it needs to do some `CRLF` -> `LF` conversion and the FS overall seems slower with git. I don't know if node's `child_process` has much overhead, but I think it's fine in this case.

**Comment by Forgo7ten** [comment]
> I think you forgot the `git add` and `git commit` steps.
> 
> https://github.com/APKLab/APKLab/blob/b099ec44458c78fdae2532e7bd30b72b32eb21bd/src/tools/git.ts#L32
> 
> From my experience, this is always slower on Windows as it needs to do some `CRLF` -> `LF` conversion and the FS overall seems slower with git. I don't know if node's `child_process` has much overhead, but I think it's fine in this case.

Sorry, I'm sure it's normal.
