### ISSUE TITLE
Option to not initialise GIT repo

### ISSUE THREAD

**Issue by mrthaggar** [APKLab/APKLab#171]
I've been using APKLab for a while now, and it's great, so kudos!

However, often the decompile process takes a minute or so, and then I'm stuck waiting for over ten minute for the GIT repo to initialise.  And I don't actually need the GIT repo.

Would it be possible to add an option to **not** create the GIT repo after decompiling?

Thanks

**Comment by Surendrajat** [comment]
Duplicates #144

There's always a preference for that
![image](https://user-images.githubusercontent.com/11215000/179228451-1c085c72-f75e-4ab9-b82f-5e006757d7ab.png)

Not sure if disabling it will benefit more people.
