### ISSUE TITLE
please use encode=utf8 

### ISSUE THREAD

**Issue by c01ns** [APKLab/APKLab#174]
![image](https://user-images.githubusercontent.com/44087084/180361541-31fe0224-cb47-4c08-8fee-47bc3ee18184.png)

if the project path have other encode, rebuild apk error

**Comment by Coinswang** [comment]
W: i:\APKLAB\愤�?�\res: error: failed to open directory: 系统找不到指定的文件�? (2).
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_27214292395593837561120380704686606931.tmp, compile, --dir, i:\APKLAB\��ŭ��С��2\res, --legacy, -o, i:\APKLAB\��ŭ��С��2\build\resources.zip]
Rebuilding process exited with code 1

**Comment by Onekki** [comment]
不用中文路径试试

**Comment by Surendrajat** [comment]
This is an issue ApkTool, so it should be reported there.
