### ISSUE TITLE
Rename package name feature

### ISSUE THREAD

**Issue by weeebdev** [APKLab/APKLab#178]
**Is your feature request related to a problem? Please describe.**
Add a feature to rename a package name

**Describe the solution you'd like**
Don't know how

**Describe alternatives you've considered**
Couldn't do it manually

**Additional context**
Please

**Comment by Surendrajat** [comment]
Ideally this should be a part of https://github.com/LoyieKing/Smalise (if at all) and given the complexity involved in parsing all smali files and renaming class paths, I'll not be adding it in here.
