### ISSUE TITLE
Try to merge classes unless there are conflicting methods

### ISSUE THREAD

**Issue by canewsin** [APKLab/APKLab#182]
Currently If there is conflicting class, conflicting class will be renamed to some random class name. 

But for multi dex(most of them are) apps, classes are split into multiple dex files, where same class exists in multiple files, but with different methods. this makes unnecessary code complexity to viewer.

**Comment by Surendrajat** [comment]
Sorry for super late response, but this does not seem like something to be done here. Depending on smali or java source, it's either apktool or Jadx related issue so you need to open it there.
