### ISSUE TITLE
Open APK didn't worked

### ISSUE THREAD

**Issue by nirmalrevarcenturylink** [APKLab/APKLab#190]
Open APK didn't worked.
I am using Apple M1-Pro
Visual Studio version:  1.78.2 
APKLab. version: 1.6.1

https://github.com/APKLab/APKLab/assets/72856780/da985efe-2283-4e4f-8778-6c000f3c0dd2

**Comment by carlv-stripe** [comment]
same, also apple m1 pro

**Comment by Surendrajat** [comment]
This is weird. It works on M1 for me. Not sure what's different for M1 Pro. Can you try to debug it?

**Comment by nirmalrevarcenturylink** [comment]
For me it was working before but before 4 days ago it stopped working automatically, 
I uninstall everything and reinstalled again, checked by installing previous version a swell, but still issue not resolved

**Comment by wraithbeam** [comment]
Same problem. 
Log: getaddrinfo ENOTFOUND apklab.surendrajat.xyz

**Comment by andiradulescu** [comment]
Same behavior for me on 1.6.1. But, it works on 1.6.0.

You can install 1.6.0 by pressing the dropdown arrow next to "Uninstall" and "Install Another Version..." then select 1.6.0, and "Reload".

**Comment by Surendrajat** [comment]
It seems like a network issue. APKLab checks for update every time you open an APK and tries to fetch update data from `apklab.surendrajat.xyz`. So either you're offline or you can't access this URL.

I'll try to fix this issue in the next version. Meanwhile, try to disable `Apklab: Update Tools` setting.

**Comment by nirmalrevarcenturylink** [comment]
@Surendrajat  Thanks for quick fix
