### ISSUE TITLE
OpenAPK cannot find the file?

### ISSUE THREAD

**Issue by jamesmac10** [APKLab/APKLab#197]
I am unable to open an APK to use with APKLab.
I am including an mp4 to show the issue. All I did was install it in vscodium and I made sure all the dependencies were installed and available. But no matter where I move the APK file to, when I try to open it with OpenAPK it always says it cannot find the file. Am I missing something obvious? Thanks in advance for any help you can give me.

    /////////////                db@xdesktop
         /////////////////////            -----------
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64
    //////7676767676*//////////////       Host: X570 AORUS ELITE WIFI -CF
   /////76767//7676767//////////////      Kernel: 6.2.6-76060206-generic
  /////767676///*76767///////////////     Uptime: 10 hours, 31 mins
 ///////767676///76767.///7676*///////    Packages: 2864 (dpkg), 18 (flatpak)
/////////767676//76767///767676////////   Shell: bash 5.1.16
//////////76767676767////76767/////////   Resolution: 1920x1080, 1920x1080, 1920x1080
///////////76767676//////7676//////////   DE: GNOME 42.5
////////////,7676,///////767///////////   WM: Mutter
/////////////*7676///////76////////////   WM Theme: Pop
///////////////7676////////////////////   Theme: Orchis-Dark-Compact [GTK2/3]
 ///////////////7676///767////////////    Icons: cyberpunk-technotronic-icon-theme-main
  //////////////////////'////////////     Terminal: x-terminal-emul
   //////.7676767676767676767,//////      CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz
    /////767676767676767676767/////       GPU: NVIDIA GeForce RTX 3070 Ti
      ///////////////////////////         Memory: 4054MiB / 32026MiB
         /////////////////////
             /////////////
https://github.com/APKLab/APKLab/assets/20391665/68fbbedf-2f9c-4d16-9672-7dbde3b40a0a

**Comment by Surendrajat** [comment]
> Error: spawn java ENOENT

As you can see you don't have Java Installed. Install openjdk and try again.
