### ISSUE TITLE
Adb install will fail if the filename contains space

### ISSUE THREAD

**Issue by myzhan** [APKLab/APKLab#199]
**Describe the bug**
Adb install will fail if the filename contains space. 

**To Reproduce**
1. Rename the name of apk and insert space. Like "foo bar.apk".
2. Right click on the apk file, and select "APKLab: Install the APK".
3. The generate command line will be "adb install foo bar.apk", and it will fail.

**Expected behavior**
Successfully install the apk.

**Console Logs**
<details>

```bash
$ adb install -r foo bar.apk
Error: spawn adb ENOENT
```

</details>

**System Information:**

**Additional context**

**Comment by Surendrajat** [comment]
You need to install adb

**Comment by myzhan** [comment]
ADB is already installed. The error happens bacause of the filename contains space, the full filename is "foo bar.apk" with a space character.

**Comment by Surendrajat** [comment]
Does it work without space in filename?
Anyhow `Error: spawn adb ENOENT` means it can't find `adb`.

**Comment by myzhan** [comment]
> Does it work without space in filename?
Yes it works.

And I think the non-zero exit code of adb may throw this error.
