### ISSUE TITLE
error: resource android:bool/config_cecRcProfileTvNone_default is private.

### ISSUE THREAD

**Issue by dmitryuk** [APKLab/APKLab#202]
**Describe the bug**
I decompile file, make my changes and want to build it back.
What I do wrong? I tried debug and no debug, or aapt2

**To Reproduce**

1. Rebuild APK

**Expected behavior**
Build successful

**Console Logs**

<details>
Using aapt2 - setting 'debuggable' attribute to 'true' in AndroidManifest.xml
W: /res/values/bools.xml:32: error: resource android:bool/config_cecRcProfileTvNone_default is private.
W: /res/values/bools.xml:42: error: resource android:bool/config_autoBrightnessResetAmbientLuxAfterWarmUp is private.
W: /res/values/colors.xml:86: error: resource android:color/accessibility_magnification_thumbnail_container_stroke_color is private.
W: /res/values/dimens.xml:286: error: resource android:dimen/preference_screen_top_margin is private.
W: /res/values/dimens.xml:287: error: resource android:dimen/primary_content_alpha_device_default is private.
W: /res/values/dimens.xml:288: error: resource android:dimen/primary_content_alpha_material_light is private.
W: /res/values/dimens.xml:310: error: resource android:dimen/chooser_row_text_option_translate is private.
W: /res/values/dimens.xml:497: error: resource android:dimen/navigation_bar_height is private.
W: /res/values/dimens.xml:498: error: resource android:dimen/notification_headerless_line_height is private.
W: /res/values/dimens.xml:507: error: resource android:dimen/car_keyline_4 is private.
W: /res/values/dimens.xml:1273: error: resource android:dimen/lock_pattern_fade_away_gradient_width is private.
W: /res/values/dimens.xml:1385: error: resource android:dimen/car_large_avatar_badge_size is private.
W: /res/values/dimens.xml:1386: error: resource android:dimen/car_large_avatar_size is private.
W: /res/values/dimens.xml:1667: error: resource android:dimen/search_view_preferred_height is private.
W: /res/values/dimens.xml:1674: error: resource android:dimen/secondary_content_alpha_device_default is private.
W: /res/values/integers.xml:27: error: resource android:integer/config_accessibilityColorMode is private.
W: /res/values/styles.xml:40: error: resource android:anim/ic_signal_wifi_transient_animation_1 is private.
W: /res/values/styles.xml:41: error: resource android:anim/slow_fade_in is private.
W: /res/values/styles.xml:40: error: resource android:anim/ic_signal_wifi_transient_animation_1 is private.
W: /res/values/styles.xml:41: error: resource android:anim/slow_fade_in is private.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_4593745244162142328174612221750625063.tmp, link, -o, /tmp/APKTOOL6110225411968156798.tmp, --package-id, 127, --min-sdk-version, 28, --target-sdk-version, 28, --version-code, 1, --version-name, 1.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --enable-sparse-encoding, -e, /tmp/APKTOOL6924816672390325013.tmp, -0, arsc, -I, /home/coden/.local/share/apktool/framework/1.apk, --manifest, /AndroidManifest.xml, /build/resources.zip]
Rebuilding process exited with code 1
</details>

**System Information:**

- OS: Ubuntu 22
- VSCode Version: 1.67.1

**Additional context**

**Comment by Surendrajat** [comment]
This is an APKTool issue and looks like this has been fixed(https://github.com/iBotPeaches/Apktool/pull/3396) but not released yet. Keep an eye out for next APKTool release.
